import { FlatCompat } from "@eslint/eslintrc";
import js from "@eslint/js";
import reactHooks from "eslint-plugin-react-hooks";
import globals from "globals";
import tseslint from "typescript-eslint";

/**
 * One root config for the whole monorepo.
 *
 * ESLint's flat config resolution walks up from the file being linted to find
 * this, so every workspace's `lint` script (`eslint .`, run with that
 * workspace as cwd) picks it up automatically — no per-workspace config file,
 * matching the "don't create a package for two similar files" guidance already
 * followed elsewhere in this repo.
 */
const compat = new FlatCompat({ baseDirectory: import.meta.dirname });

export default tseslint.config(
  {
    ignores: [
      "**/node_modules/**",
      "**/.next/**",
      "**/.turbo/**",
      "**/dist/**",
      "**/coverage/**",
      // Generated by Prisma; not source we own or want linted.
      "**/prisma/migrations/**",
      // Regenerated by Next on every build; linting it means linting Next's own
      // codegen, not ours.
      "**/next-env.d.ts",
      // Playwright's own output: reports, traces, and the saved login session.
      "**/playwright-report/**",
      "**/test-results/**",
      "**/.auth/**",
    ],
  },

  js.configs.recommended,
  ...tseslint.configs.recommended,

  {
    languageOptions: {
      globals: { ...globals.node },
    },
    rules: {
      // Prisma/tRPC's inferred types are frequently intentionally unnamed; the
      // TS compiler (`noUnusedLocals`/`noUnusedParameters`, already strict in
      // tsconfig.base.json) is the real enforcement for unused bindings, so this
      // is relaxed here rather than duplicated with a slightly different rule
      // set that can disagree with `tsc`.
      "@typescript-eslint/no-unused-vars": [
        "warn",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],
    },
  },

  // Next.js apps only: React rules, hooks rules, and Next's own recommended set.
  ...compat
    .extends("next/core-web-vitals", "next/typescript")
    .map((config) => ({
      ...config,
      files: ["apps/storefront/**/*.{ts,tsx}", "apps/admin/**/*.{ts,tsx}"],
    })),
  {
    files: ["apps/storefront/**/*.{ts,tsx}", "apps/admin/**/*.{ts,tsx}"],
    plugins: { "react-hooks": reactHooks },
    rules: {
      ...reactHooks.configs.recommended.rules,
    },
  },

  // Server-only code: no React, no browser globals to worry about.
  {
    files: ["apps/api/**/*.ts", "packages/**/*.ts"],
    languageOptions: {
      globals: { ...globals.node },
    },
  },
);
